### ISSUE TITLE
调用的时候出现一些问题

### ISSUE THREAD

**Issue by tron19920125** [namco1992/voicetools#6]
Traceback (most recent call last):
  File "testt.py", line 7, in <module>
    audio = bv.tts('你好')  # 返回 MP3 格式二进制数据，可选参数见百度语音文档
  File "/usr/local/lib/python2.7/dist-packages/voicetools/api.py", line 133, in tts
    return baiduclient.tts(params)
  File "/usr/local/lib/python2.7/dist-packages/voicetools/clients.py", line 79, in tts
    raise ErrNo.tts_err_no.get(response['err_no'], APIError)(err_msg)
voicetools.exceptions.VerifyError: err_msg: authentication failed.

**Comment by namco1992** [comment]
根据 Traceback 来看，是百度语音 api 的鉴权未通过，再检查一下你的api key 和 secret key 是否正确吧。
[百度语音官网地址](http://yuyin.baidu.com)

PS：百度语音的 key 跟百度 api store 的不是同一套哦。

**Comment by tron19920125** [comment]
检查过了哈，语音识别没问题 但是合成就报错 应该不是我的KEY的问题 怪怪的

**Comment by tron19920125** [comment]
File "/usr/local/lib/python2.7/dist-packages/voicetools/api.py", line 52, in ask_turing
    raise APIError('Cannot handle this ret code: %s' % code)


图灵机器人也有问题 查过不是KEY的问题

**Comment by namco1992** [comment]
文档描述有误，已修正该问题。
