### ISSUE TITLE
python3导入包报错

### ISSUE THREAD

**Issue by jason-img** [namco1992/voicetools#7]
大佬你好，刚刚shell试了一下，python3导入包就报错，python2正常，请问是什么情况呢？

---------------------------

Traceback (most recent call last):
  File "D:\workspace\3gg\Python\voice\voice_test.py", line 1, in <module>
    import voicetools
  File "C:\Python36\lib\site-packages\voicetools\__init__.py", line 13, in <module>
    from .api import Wolfram, TuringRobot, BaiduVoice
  File "C:\Python36\lib\site-packages\voicetools\api.py", line 97
    except Exception, e:
                    ^
SyntaxError: invalid syntax

**Comment by namco1992** [comment]
你好，

非常抱歉，当时写这个包的时候并没有兼容 python3，也没有在 python3 的环境下测试。如果你有兴趣的话，可以考虑提 pull request 来修复这个问题，或者近期我来修复。

其实你可以看到源码非常简单，我相信兼容 python3 应该不是一个很困难的工作。

Best regards,

Gong Mengnan
